name = "claude-relay-frontend"
compatibility_date = "2025-07-25"

[env.production.vars]
NUXT_PUBLIC_API_BASE_URL = "https://claude-relay-backend.117yelixin.workers.dev"

[env.preview.vars]
NUXT_PUBLIC_API_BASE_URL = "https://claude-relay-backend-preview.117yelixin.workers.dev"
