name = "claude-relay-backend"
main = "src/index.ts"
compatibility_date = "2025-07-25"

# 管理中心统一 KV 存储（存储账号、配置、tokens等所有数据）
[[kv_namespaces]]
binding = "CLAUDE_RELAY_ADMIN_KV"
id = "3a7a9b425a5a4598af2a681526156af8"
preview_id = "3a7a9b425a5a4598af2a681526156af8"

# 定时任务配置 - 每6小时刷新一次 token
[triggers]
crons = ["0 */6 * * *"]

# 生产环境配置
[vars]
NODE_ENV = "production"
FRONTEND_URL = "https://ccproxy.winter-017.workers.dev"
# 管理员认证
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "password123"

# 预览环境配置
[env.preview]
name = "claude-relay-backend-preview"

[env.preview.vars]
NODE_ENV = "preview"
FRONTEND_URL = "https://claude-relay-frontend.pages.dev"
# 管理员认证
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "password123"
